name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ ubuntu, windows ]
        node-version: [16.x, 18.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g npm@9
    - run: npm ci
    - run: npm run lint
    - run: npm run test
